# Generated by Django 4.0.2 on 2022-02-05 12:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0001_initial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boro_code', models.FloatField()),
                ('boro_name', models.CharField(max_length=254)),
                ('county_fip', models.CharField(max_length=254)),
                ('ntacode', models.CharField(max_length=254)),
                ('ntaname', models.CharField(max_length=254)),
                ('shape_area', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='PointsInPolygon',
        ),
    ]
