# Generated by Django 4.0.2 on 2022-02-05 13:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0002_neighborhoods_delete_pointsinpolygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=158)),
                ('admin_leve', models.CharField(max_length=1)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
