# Generated by Django 4.0.2 on 2022-02-05 14:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0003_iran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iran2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=10)),
                ('code', models.IntegerField(null=True)),
                ('fclass', models.CharField(max_length=28)),
                ('population', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Iran',
        ),
    ]
