# Generated by Django 4.0.2 on 2022-02-05 14:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0004_iran2_delete_iran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iran2',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
