# Generated by Django 4.0.2 on 2022-02-05 14:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0005_alter_iran2_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='OstanIran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_0', models.IntegerField()),
                ('iso', models.CharField(max_length=3)),
                ('name_0', models.CharField(max_length=75)),
                ('id_1', models.IntegerField()),
                ('name_1', models.CharField(max_length=75)),
                ('varname_1', models.CharField(max_length=150)),
                ('nl_name_1', models.CharField(max_length=50)),
                ('hasc_1', models.CharField(max_length=15)),
                ('cc_1', models.CharField(max_length=15)),
                ('type_1', models.CharField(max_length=50)),
                ('engtype_1', models.CharField(max_length=50)),
                ('validfr_1', models.CharField(max_length=25)),
                ('validto_1', models.CharField(max_length=25)),
                ('remarks_1', models.CharField(max_length=125)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
