# Generated by Django 4.0.2 on 2022-02-05 14:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0006_ostaniran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ostaniran',
            name='nl_name_1',
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='cc_1',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='engtype_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='hasc_1',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='id_0',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='id_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='iso',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='name_0',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='name_1',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='remarks_1',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='shape_area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='shape_leng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='type_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='validfr_1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='validto_1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='varname_1',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
