# Generated by Django 4.0.2 on 2022-02-05 15:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0008_ostaniran_nl_name_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ostaniran',
            name='cc_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='nl_name_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='remarks_1',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='ostaniran',
            name='varname_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
