# Generated by Django 4.0.2 on 2022-02-05 17:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0010_marker_delete_iran2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ostaniran',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
