# Generated by Django 4.0.2 on 2022-02-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0011_alter_ostaniran_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ostaniran',
            name='name_1',
            field=models.CharField(default='ir', max_length=75),
            preserve_default=False,
        ),
    ]
