# Generated by Django 4.0.2 on 2022-02-08 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0013_marker_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Neighborhoods',
        ),
    ]
