# Generated by Django 4.0.2 on 2022-02-08 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0015_remove_ostaniran_id_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ostaniran',
            name='cc_1',
        ),
        migrations.RemoveField(
            model_name='ostaniran',
            name='engtype_1',
        ),
        migrations.RemoveField(
            model_name='ostaniran',
            name='hasc_1',
        ),
        migrations.RemoveField(
            model_name='ostaniran',
            name='id_1',
        ),
        migrations.RemoveField(
            model_name='ostaniran',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='ostaniran',
            name='name_0',
        ),
        migrations.RemoveField(
            model_name='ostaniran',
            name='nl_name_1',
        ),
        migrations.RemoveField(
            model_name='ostaniran',
            name='remarks_1',
        ),
        migrations.RemoveField(
            model_name='ostaniran',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='ostaniran',
            name='shape_leng',
        ),
        migrations.RemoveField(
            model_name='ostaniran',
            name='type_1',
        ),
        migrations.RemoveField(
            model_name='ostaniran',
            name='validfr_1',
        ),
        migrations.RemoveField(
            model_name='ostaniran',
            name='validto_1',
        ),
        migrations.RemoveField(
            model_name='ostaniran',
            name='varname_1',
        ),
    ]
