# Generated by Django 4.0.2 on 2022-02-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0016_remove_ostaniran_cc_1_remove_ostaniran_engtype_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ostaniran',
            old_name='name_1',
            new_name='name',
        ),
    ]
