# Generated by Django 4.0.2 on 2022-02-08 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0019_alter_marker_slug_alter_ostaniran_geom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points_in_polygon.marker')),
            ],
        ),
        migrations.AddField(
            model_name='ostaniran',
            name='connection',
            field=models.ManyToManyField(blank=True, null=True, related_name='connections', through='points_in_polygon.Geometry', to='points_in_polygon.Marker'),
        ),
        migrations.AddField(
            model_name='geometry',
            name='polygon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points_in_polygon.ostaniran'),
        ),
    ]
