# Generated by Django 4.0.2 on 2022-02-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0020_geometry_ostaniran_connection_geometry_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='polygon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='points_in_polygon.ostaniran'),
        ),
    ]
