# Generated by Django 4.0.2 on 2022-02-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0021_marker_polygon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ostaniran',
            name='connection',
        ),
        migrations.DeleteModel(
            name='Geometry',
        ),
    ]
