# Generated by Django 4.0.2 on 2022-02-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0023_alter_marker_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='polygon',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
    ]
