# Generated by Django 4.0.2 on 2022-02-09 23:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0024_alter_marker_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ostaniran',
            name='markers',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
