# Generated by Django 4.0.2 on 2022-02-09 23:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points_in_polygon', '0025_ostaniran_markers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ostaniran',
            name='markers',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
    ]
